name: flutter_carplaybr
description: Flutter Apps are now on Apple CarPlay. This package aims to make it safe to use iPhone apps made with Flutter in the car by integrating with CarPlay.
version: 1.1.12
homepage: https://github.com/Fix-Pay/flutter_carplaybr#readme
repository: https://github.com/Fix-Pay/flutter_carplaybr
issue_tracker: https://github.com/Fix-Pay/flutter_carplaybr/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
